export const BLOGS_LIST_REQUEST= "BLOGS_LIST_REQUEST"
export const BLOGS_LIST_SUCCESS= "BLOGS_LIST_SUCCESS"
export const BLOGS_LIST_FAIL= "BLOGS_LIST_FAIL"

export const BLOG_DETAIL_REQUEST= "BLOG_DETAIL_REQUEST"
export const BLOG_DETAIL_SUCCESS= "BLOG_DETAIL_SUCCESS"
export const BLOG_DETAIL_FAIL= "BLOG_DETAIL_FAIL"

export const BLOG_LIKE_REQUEST= "BLOG_LIKE_REQUEST"
export const BLOG_LIKE_SUCCESS= "BLOG_LIKE_SUCCESS"
export const BLOG_LIKE_FAIL= "BLOG_LIKE_FAIL"